simplify the rice script by use only base16

diff --git a/scripts/.local/bin/rice b/scripts/.local/bin/rice
--- a/scripts/.local/bin/rice
+++ b/scripts/.local/bin/rice
@@ -1,8 +1,6 @@
 #!/bin/bash
 
-# file names
 C_RICINIG="$XDG_CONFIG_HOME/ricing"
-c_xresources="$C_RICINIG/theme.Xresources"
 c_nvim="$C_RICINIG/colorscheme.lua"
 c_zshrc="$C_RICINIG/theme.zsh"
 c_tmux="$C_RICINIG/theme-tmux.conf"
@@ -17,8 +15,6 @@ c_foot="$C_RICINIG/foot-theme.ini"
 c_waybar="$C_RICINIG/waybar.css"
 
 themes="base16-gruvbox-dark-hard
-catppuccin-mocha
-tokyonight
 base16-default-dark
 base16-ia-dark
 base16-monokai
@@ -37,166 +33,73 @@ base16-tomorrow-night
 base16-twilight
 base16-oxocarbon-dark"
 
-if [ -n "$1" ]; then
-  if echo "$themes" | grep -q "^$1$"; then
-    theme_name="$1"
+pick_theme() {
+  local selected
+
+  if [ -n "${1:-}" ]; then
+    selected="$1"
   else
-    echo "Error: Theme '$1' not found in themes list"
+    selected="$(echo "$themes" | fzf-menu --prompt='🎨 Choose a theme ~ ')"
+  fi
+
+  [ -n "$selected" ] || exit 0
+
+  if ! echo "$themes" | grep -q "^$selected$"; then
+    echo "Error: Theme '$selected' not found in selected themes list"
     exit 1
   fi
-else
-  theme_name="$(echo "$themes" | fzf-menu --prompt='🎨 Choose a theme ~ ')"
-  if [ ! "$theme_name" ]; then
-    exit
-  fi
-fi
 
-update_xresources() {
-  truncate -s 0 "$c_xresources"
-
-  echo "! vim: ft=xdefaults" >>"$c_xresources"
-  echo "" >>"$c_xresources"
-  echo "" >>"$c_xresources"
-
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    echo "# include \"catppuccin-xresources/themes/mocha.Xresources\"" >>"$c_xresources"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    echo "# include \"tokyonight.nvim/extras/xresources/tokyonight_night.Xresources\"" >>"$c_xresources"
-  else
-    echo "# include \"base16-xresources/xresources/$theme_name.Xresources\"" >>"$c_xresources"
-  fi
-
-  xrdb \
-    -I"${XDG_CONFIG_HOME}/x11" -I"${XDG_CONFIG_HOME}/ricing" -I"${HOME}/.local/src" \
-    -merge "$c_xresources"
+  theme_name="$selected"
 }
 
 update_tmux() {
-  truncate -s 0 "$c_tmux"
+  {
+    echo "source-file \"\$XDG_DATA_HOME/tmux/plugins/tinted-tmux/colors/$theme_name.conf\""
+    echo "set -g @colors-base16 '${theme_name#base16-}'"
+  } >"$c_tmux"
 
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    echo 'set -g @catppuccin_window_status_style "none"' >>"$c_tmux"
-    echo 'set -g @catppuccin_flavor "mocha"' >>"$c_tmux"
-    echo "run \"\$XDG_DATA_HOME/tmux/plugins/catppuccin/catppuccin.tmux\"" >>"$c_tmux"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    echo "source-file \"\$HOME/.local/src/tokyonight.nvim/extras/tmux/tokyonight_night.tmux\"" >>"$c_tmux"
-  else
-    echo "source-file \"\$XDG_DATA_HOME/tmux/plugins/tinted-tmux/colors/$theme_name.conf\"" >>"$c_tmux"
-    echo "set -g @colors-base16 '${theme_name#base16-}'" >>"$c_tmux"
-  fi
-
-  [ "$(pidof tmux)" ] &&
-    tmux source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"
+  [ "$(pidof tmux)" ] && tmux source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"
 }
 
 update_nvim() {
-  truncate -s 0 "$c_nvim"
-
-  if [ "$theme_name" == "tokyonight" ]; then
-    echo "vim.cmd[[silent! colorscheme tokyonight-night]]" >>"$c_nvim"
-  else
-    echo "vim.cmd[[silent! colorscheme ""$theme_name""]]" >>"$c_nvim"
-  fi
-
+  echo "vim.cmd[[silent! colorscheme $theme_name]]" >"$c_nvim"
   nvr -c ":silent! colorscheme $theme_name<cr>"
 }
 
 update_zsh() {
-  truncate -s 0 "$c_zshrc"
-
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    awk '
-      /🌿 Mocha/ {flag=1}
-      flag && /Bash\/Zsh/ {subflag=1; next}
-      flag && subflag && /Fish/ {subflag=0; flag=0}
-      flag && subflag {print}
-    ' "$HOME/.local/src/catppuccin-fzf/README.md" | sed '/^```/d' >"$c_zshrc"
-
-    echo 'export BAT_THEME="Catppuccin Mocha"' >>"$c_zshrc"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    echo "source \"\$HOME/.local/src/tokyonight.nvim/extras/fzf/tokyonight_night.sh\"" >"$c_zshrc"
-    echo '' >>"$c_zshrc"
-    echo 'export BAT_THEME="tokyonight_night"' >>"$c_zshrc"
-  else
-    echo "source \"$HOME/.local/src/tinted-fzf/sh/$theme_name.sh\"" >"$c_zshrc"
-    echo '' >>"$c_zshrc"
-    echo 'export BAT_THEME="base16"' >>"$c_zshrc"
-  fi
+  {
+    echo "source \"$HOME/.local/src/tinted-fzf/sh/$theme_name.sh\""
+    echo
+    echo 'export BAT_THEME="base16"'
+  } >"$c_zshrc"
 
   killall -u "$(whoami)" -s USR1 zsh
 }
 
-update_st() {
-  killall -s USR1 st
-}
-
 update_qutebrowser() {
-  truncate -s 0 "$c_qutebrowser"
-
-  echo "from typing import cast" >>"$c_qutebrowser"
-  echo "from qutebrowser.config.configfiles import ConfigAPI" >>"$c_qutebrowser"
-  echo "from qutebrowser.config.config import ConfigContainer" >>"$c_qutebrowser"
-  echo "" >>"$c_qutebrowser"
-
-  echo "config = cast(ConfigAPI, config)  # type: ignore  # noqa: F821" >>"$c_qutebrowser"
-  echo "c = cast(ConfigContainer, c)  # type: ignore  # noqa: F821" >>"$c_qutebrowser"
-  echo "" >>"$c_qutebrowser"
-
-  if [ "$theme_name" = "catppuccin-mocha" ] || [ "$theme_name" = "tokyonight" ]; then
-    echo "import catppuccin" >>"$c_qutebrowser"
-    echo "" >>"$c_qutebrowser"
-    echo "catppuccin.setup(c, 'mocha', True)" >>"$c_qutebrowser"
-  else
-    echo "config.source('$XDG_CONFIG_HOME/qutebrowser/base16-qutebrowser/themes/default/$theme_name.config.py')" >>"$c_qutebrowser"
-  fi
-
-  echo 'c.colors.webpage.bg = "white"' >>"$c_qutebrowser"
+  {
+    echo "config.source('$XDG_CONFIG_HOME/qutebrowser/base16-qutebrowser/themes/minimal/$theme_name.config.py')"
+    echo 'c.colors.webpage.bg = "white"'
+  } >"$c_qutebrowser"
 
   [ "$(pgrep -f qutebrowser)" ] && qutebrowser :config-source
-}
-
-update_dwm() {
-  dwm-msg run_command xrdb
 }
 
 update_wallpaper() {
   find /mnt/hdd01/media/photos/wallpapers/* | shuf -n1 | xargs setbg
 }
 
-update_dwm() {
-  dwm-msg run_command xrdb
-}
-
 update_lazygit() {
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    cp "$HOME/.local/src/catppuccin-lazygit/themes-mergable/mocha/teal.yml" "$c_lazygit"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    cp "$HOME/.local/src/tokyonight.nvim/extras/lazygit/tokyonight_night.yml" "$c_lazygit"
-  else
-    cp "$HOME/.local/src/base16-lazygit/colors/$theme_name.yml" "$c_lazygit"
-  fi
+  cp "$HOME/.local/src/base16-lazygit/colors/$theme_name.yml" "$c_lazygit"
 }
 
 update_zathura() {
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    cp "$HOME/.local/src/catppuccin-zathura/src/catppuccin-mocha" "$c_zathura"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    cp "$HOME/.local/src/tokyonight.nvim/extras/zathura/tokyonight_night.zathurarc" "$c_zathura"
-  else
-    cp "$HOME/.local/src/base16-zathura/build_schemes/recolors/$theme_name.config" "$c_zathura"
-  fi
+  cp "$HOME/.local/src/base16-zathura/build_schemes/recolors/$theme_name.config" "$c_zathura"
 }
 
 update_dunst() {
   pkill -9 dunst
-
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    cp "$HOME/.local/src/catppuccin-dunst/themes/mocha.conf" "$c_dunst"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    cp "$HOME/.local/src/tokyonight.nvim/extras/dunst/tokyonight_night.dunstrc" "$c_dunst"
-  else
-    cp "$HOME/.local/src/base16-dunst/themes/$theme_name.dunstrc" "$c_dunst"
-  fi
+  cp "$HOME/.local/src/base16-dunst/themes/$theme_name.dunstrc" "$c_dunst"
 
   local frame_color
   local highlight_color
@@ -212,137 +115,40 @@ update_dunst() {
 }
 
 update_delta() {
-  truncate -s 0 "$c_delta"
-
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    echo "[include]" >>"$c_delta"
-    echo "  path = $XDG_CONFIG_HOME/git/catppuccin-delta/catppuccin.gitconfig" >>"$c_delta"
-    echo "[delta]" >>"$c_delta"
-    echo "  features = catppuccin-mocha" >>"$c_delta"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    echo "[include]" >>"$c_delta"
-    echo "  path = $HOME/.local/src/tokyonight.nvim/extras/delta/tokyonight_night.gitconfig" >>"$c_delta"
-  else
-    echo "[delta]" >>"$c_delta"
-    echo "  syntax-theme = base16" >>"$c_delta"
-  fi
-
+  {
+    echo "[delta]"
+    echo "  syntax-theme = base16"
+  } >"$c_delta"
 }
 
 update_alacritty() {
-  truncate -s 0 "$c_alacritty"
-
-  echo "[general]" >>"$c_alacritty"
-  echo "" >>"$c_alacritty"
-
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    # catppuccin-alacritty typically ships toml/yaml; adjust filename if your repo differs
-    echo "import = [\"$HOME/.config/alacritty/themes/catppuccin-alacritty/catppuccin-mocha.toml\"]" >>"$c_alacritty"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    # tokyonight.nvim extras usually include an alacritty toml
-    echo "import = [\"$HOME/.local/src/tokyonight.nvim/extras/alacritty/tokyonight_night.toml\"]" >>"$c_alacritty"
-  elif [[ "$theme_name" == base16-* ]]; then
-    # tinted-terminal base16 themes
-    echo "import = [\"$HOME/.local/src/tinted-terminal/themes/alacritty/$theme_name.toml\"]" >>"$c_alacritty"
-  else
-    # fallback: try same name as-is in tinted-terminal
-    echo "import = [\"$HOME/.local/src/tinted-terminal/themes/alacritty/$theme_name.toml\"]" >>"$c_alacritty"
-  fi
+  {
+    echo "[general]"
+    echo "import = [\"$HOME/.local/src/tinted-terminal/themes/alacritty/$theme_name.toml\"]"
+  } >"$c_alacritty"
 }
 
 update_foot() {
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    cp "$HOME/.local/src/catppuccin-foot/themes/catppuccin-mocha.ini" "$c_foot"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    awk '
-      /^\[cursor\]/ { in_cursor=1; next }
-      in_cursor && /^color=/ { cursor_val=substr($0, 7); next }
-      in_cursor && /^$/ { in_cursor=0; next }
-      /^\[colors\]/ { print; if (cursor_val) print "cursor=" cursor_val; next }
-      !in_cursor { print }
-    ' "$HOME/.local/src/tokyonight.nvim/extras/foot/tokyonight_night.ini" >"$c_foot"
-  elif [[ "$theme_name" == base16-* ]]; then
-    cp "$HOME/.local/src/tinted-terminal/themes/foot/$theme_name.ini" "$c_foot"
-  else
-    cp "$HOME/.local/src/tinted-terminal/themes/foot/$theme_name.ini" "$c_foot"
-  fi
+  cp "$HOME/.local/src/tinted-terminal/themes/foot/$theme_name.ini" "$c_foot"
 }
 
 update_waybar() {
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    cp "$HOME/.config/waybar/themes/catppuccin.css" "$c_waybar"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    cp "$HOME/.config/waybar/themes/tokyonight.css" "$c_waybar"
-  else
-    local src="/home/ashraf/.local/src/base16-waybar/colors/$theme_name.css"
-    awk '
-      /@define-color base00/ { base00=$3; gsub(";", "", base00) }
-      /@define-color base01/ { base01=$3; gsub(";", "", base01) }
-      /@define-color base02/ { base02=$3; gsub(";", "", base02) }
-      /@define-color base03/ { base03=$3; gsub(";", "", base03) }
-      /@define-color base04/ { base04=$3; gsub(";", "", base04) }
-      /@define-color base05/ { base05=$3; gsub(";", "", base05) }
-      /@define-color base06/ { base06=$3; gsub(";", "", base06) }
-      /@define-color base07/ { base07=$3; gsub(";", "", base07) }
-      /@define-color base08/ { base08=$3; gsub(";", "", base08) }
-      /@define-color base09/ { base09=$3; gsub(";", "", base09) }
-      /@define-color base0A/ { base0A=$3; gsub(";", "", base0A) }
-      /@define-color base0B/ { base0B=$3; gsub(";", "", base0B) }
-      /@define-color base0C/ { base0C=$3; gsub(";", "", base0C) }
-      /@define-color base0D/ { base0D=$3; gsub(";", "", base0D) }
-      /@define-color base0E/ { base0E=$3; gsub(";", "", base0E) }
-      /@define-color base0F/ { base0F=$3; gsub(";", "", base0F) }
-      END {
-        print "@define-color background " base00 ";"
-        print "@define-color foreground " base05 ";"
-        print ""
-        print "@define-color color0 " base00 ";"
-        print "@define-color color1 " base08 ";"
-        print "@define-color color2 " base0B ";"
-        print "@define-color color3 " base0A ";"
-        print "@define-color color4 " base0D ";"
-        print "@define-color color5 " base0E ";"
-        print "@define-color color6 " base0C ";"
-        print "@define-color color7 " base05 ";"
-        print ""
-        print "@define-color color8 " base03 ";"
-        print "@define-color color9 " base08 ";"
-        print "@define-color color10 " base0B ";"
-        print "@define-color color11 " base0A ";"
-        print "@define-color color12 " base0D ";"
-        print "@define-color color13 " base0E ";"
-        print "@define-color color14 " base0C ";"
-        print "@define-color color15 " base07 ";"
-      }
-    ' "$src" >"$c_waybar"
-  fi
+  local src="$HOME/.local/src/base16-waybar/colors/$theme_name.css"
+  cp "$src" "$c_waybar"
 
   pkill -SIGUSR2 waybar
 }
 
 update_ghostty() {
-  truncate -s 0 "$c_ghostty"
-
-  if [ "$theme_name" == "catppuccin-mocha" ]; then
-    echo "theme = catppuccin-flavor.conf" >>"$c_ghostty"
-  elif [ "$theme_name" == "tokyonight" ]; then
-    echo "theme = tokyonight_night" >>"$c_ghostty"
-  elif [[ "$theme_name" == base16-* ]]; then
-    echo "theme = $HOME/.local/src/tinted-terminal/themes/ghostty/$theme_name" >>"$c_ghostty"
-  else
-    echo "theme = $theme_name" >>"$c_ghostty"
-  fi
-
+  echo "theme = $HOME/.local/src/tinted-terminal/themes/ghostty/$theme_name" >"$c_ghostty"
 }
 
 main() {
-  update_xresources
+  pick_theme "${1:-}"
 
-  # update_dwm &
   update_qutebrowser &
   update_zsh &
   update_delta &
-  # update_st &
   update_tmux &
   update_nvim &
   update_lazygit &
@@ -355,4 +161,4 @@ main() {
   update_wallpaper &
 }
 
-main
+main "$@"
