remove wallgif

diff --git a/scripts/.local/bin/setbg b/scripts/.local/bin/setbg
--- a/scripts/.local/bin/setbg
+++ b/scripts/.local/bin/setbg
@@ -1,30 +1,45 @@
 #!/bin/sh
 
+PIDFILE="/tmp/wallgif.pid"
+
 usage() {
-  cat <<EOF
-Usage: $(basename "$0") <file_path>
-setbg is a utility to set a wallpaper
-Supported formats: jpg, jpeg, png, gif, mp4, mkv, webm, youtube links
-EOF
-  exit 1
+  echo "Usage: $(basename "$0") <file_path>"
+  echo "setbg is a utility to set a wallpaper"
+  echo "Supported formats: jpg, jpeg, png, gif, mp4, mkv, webm, youtube links"
+  exit 0
 }
 
-[ $# -eq 0 ] && usage
+kill_running_xwinwrap() {
+  if [ -f "$PIDFILE" ]; then
+    pid=$(cat "$PIDFILE")
 
-case "$1" in
-http*://*)
-  file_path="$1"
-  ;;
-*)
-  file_path="$(realpath "$1")"
-  if [ ! -f "$file_path" ]; then
-    echo "file not exist"
-    exit 1
+    if kill -0 "$pid" 2>/dev/null; then
+      kill "$pid"
+      sleep 1
+    fi
+
+    rm -f "$PIDFILE"
   fi
-  ;;
-esac
+}
 
-killall xwinwrap
+get_rel_path() {
+  case "$1" in
+
+  http*://*)
+    echo "$1"
+    ;;
+  *)
+    file_path="$(realpath "$1")"
+
+    if [ ! -f "$file_path" ]; then
+      echo "file not exist"
+      exit 1
+    else
+      echo "$file_path"
+    fi
+    ;;
+  esac
+}
 
 wallgif() {
   nice xwinwrap -ni -s -nf -b -un -ovr -fdt -argb -g "$1" -- mpv \
@@ -43,26 +58,43 @@ wallgif() {
     --msg-level=vd=v,vo=v,vo/gpu/vaapi-egl=trace \
     --ytdl-format='bestvideo[height<=?1080]+bestaudio/best' \
     "$2" &
+
+  echo $! >"$PIDFILE"
 }
 
-case "$1" in
-*jpg | *jpeg | *png)
-  feh --no-fehbg --bg-fill "$file_path"
-  ;;
-*gif | *mp4 | *mkv | *webm | *youtube.com/watch*)
-  res=$(xdpyinfo | awk '/dimensions/ {print $2}')
-  wallgif "$res" "$file_path"
-  ;;
-*)
-  echo "Error: Unsupported file format"
-  exit 1
-  ;;
-esac
+create_setbg_script() {
 
-cat >~/.config/setbg <<EOF
+  cat >~/.config/setbg <<EOF
 #!/bin/sh
 
 $(command -v "$0") "$file_path"
 EOF
 
-chmod +x ~/.config/setbg
+  chmod +x ~/.config/setbg
+}
+
+main() {
+  [ $# -eq 0 ] && usage
+
+  kill_running_xwinwrap
+
+  file_path="$(get_rel_path "$1")"
+
+  case "$file_path" in
+  *jpg | *jpeg | *png)
+    feh --no-fehbg --bg-fill "$file_path"
+    ;;
+  *gif | *mp4 | *mkv | *webm | *youtube.com/watch*)
+    res=$(xdpyinfo | awk '/dimensions/ {print $2}')
+    wallgif "$res" "$file_path"
+    ;;
+  *)
+    echo "Error: Unsupported file format"
+    exit 1
+    ;;
+  esac
+
+  create_setbg_script
+}
+
+main "$@"
